import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { Dummy_meat } from '@/Components/Dummy_meat'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>hello, Next Js</h1>
          {
            Dummy_meat.map((meat) => {
                <>
                <div>{meat.name}</div>
                <Link href={`/meat/${meat.id}`}> {meat.name} 상세보기</Link>
                </>
            })
          }
          <li>
            <Link href={"/meat"}>meat 페이지</Link>
          </li>
          
        </div>
      </main>
    </>
  )
}
